services:
  django:
    build: .
    env_file:
      - .env
    command: >
      sh -c "
        ./wait-for-it.sh db:5432 -- \
        pipenv run python manage.py makemigrations && \
        pipenv run python manage.py migrate && \
        pipenv run python manage.py runserver 9000
      "
    ports:
       - "9000:9000"  
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "X7f9QpL8rVw2Y3nT"]
volumes:
  postgres_data:
