"""
Django settings for StoreSphere project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9hod7x931ee&i7n5c0r%6tj5u6y*szko3mj$k@yb3ryb^-^$5#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


UNFOLD = {
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "show_recently_visited": True,  
        "navigation": [
            {
                "title": _("Users & Groups"),
                "items": [
                    {"label": "Users", "link": "/admin/auth/user/"},
                    {"label": "Groups", "link": "/admin/auth/group/"},
                ],
            },
            {
                "titel": _("Store"),
                "items": [
                    {"label": "Products", "link": "/admin/store/products/"},
                    {"label": "Inventorys", "link": "/admin/store/inventorys/"},
                    {"label": "Inventory Products",
                        "link": "/admin/store/inventoryproducts/"},
                    {"label": "Stores", "link": "/admin/store/stores/"},
                    {"label": "Store Products", "link": "/admin/store/storeproducts/"},
                    {"label": "Requests Store To Inventory",
                        "link": "/admin/store/requestsstoretoinventory/"},
                    {"label": "Orders", "link": "/admin/store/orders/"},
                    {"label": "Order Items", "link": "/admin/store/orderitems/"},
                ],
            },
        ],
    }
}



INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'StoreSphere.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'StoreSphere.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

UNFOLD = {
    "DASHBOARD_CALLBACK": "store.views.dashboard_callback",
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "show_recently_visited": True,
        "navigation": [
            {
                "title": _("Users & Groups"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
            {
                "title": _("Store"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Products"),
                        "icon": "shopping_cart",
                        "link": reverse_lazy("admin:store_products_changelist"),
                    },
                    {
                        "title": _("Inventorys"),
                        "icon": "inventory",
                        "link": reverse_lazy("admin:store_inventorys_changelist"),
                    },
                    {
                        "title": _("Inventory Products"),
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:store_inventoryproducts_changelist"),
                    },
                    {
                        "title": _("Stores"),
                        "icon": "store",
                        "link": reverse_lazy("admin:store_stores_changelist"),
                    },
                    {
                        "title": _("Store Products"),
                        "icon": "storefront",
                        "link": reverse_lazy("admin:store_storeproducts_changelist"),
                    },
                    {
                        "title": _("Requests Store To Inventory"),
                        "icon": "request_page",
                        "link": reverse_lazy("admin:store_requestsstoretoinventory_changelist"),
                    },
                    {
                        "title": _("Orders"),
                        "icon": "receipt",
                        "link": reverse_lazy("admin:store_orders_changelist"),
                    },
                    {
                        "title": _("Order Items"),
                        "icon": "list_alt",
                        "link": reverse_lazy("admin:store_orderitems_changelist"),
                    },
                ],
            },
        ],
    }
}